server:
  port: 8000

site:
  siteName: 博客站
  version: v1.0.0
  record-number: 123213
  apiUrl: https://lidashui.top
  cdnUrl: https://www.lidashui.top
  upload:
    mode: cloud
    maxSize: 10485760
    mineType: jpg,png,bmp,jpeg,gif,webp,zip,rar,xls,xlsx,doc,docx,wav,mp4,mp3,txt
    saveName: /storage/{topic}/{year}{mon}{day}/{filesha1}{.suffix}

spring:
  application:
    name: naruto
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lidashui.top:3806/blogs?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: dashui686
    # hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 10
      #最小空闲连接，默认值 10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 2
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000ms（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      #不等于0且小于10秒，会被重置为10秒。
      #只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放(自动释放过期链接)
      idle-timeout: 600000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 640000
      #连接测试查询
      connection-test-query: SELECT 1



############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 604800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 1440
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.dashui.naruto.domain