server:
  port: 8000



spring:
  application:
    name: naruto
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.103.212.11:8787/admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

    # hikari连接池
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 10
      #最小空闲连接，默认值 10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 2
      #连接超时时间:毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 60000
      #空闲连接超时时间，默认值600000ms（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；
      #不等于0且小于10秒，会被重置为10秒。
      #只有空闲连接数大于最大连接数且空闲时间超过该值，才会被释放(自动释放过期链接)
      idle-timeout: 600000
      #连接最大存活时间.不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 640000
      #连接测试查询
      connection-test-query: SELECT 1
